# ansible-playbook 03_undercloud.yaml -i inventory -u <REMOTE_USER>
---
- name: 'Deploying the undercloud'
  become: true
  hosts: undercloud
  tasks:
    - name: 'Install director packages'
      ansible.builtin.dnf:
        name: python3-tripleoclient
        state: latest

    - name: 'Create container image preparation file'
      become_user: stack
      ansible.builtin.shell: |
        openstack tripleo container image prepare default \
        --local-push-destination \
        --output-env-file /home/stack/containers-prepare-parameter.yaml
