# ansible-playbook 03_undercloud.yaml -i inventory -u <REMOTE_USER>
---
- name: 'Deployinh the undercloud'
  hosts: undercloud
  become: true
  vars_files:
    - vars.yaml
  tasks:
    - name: 'Install director packages'
      ansible.builtin.dnf:
        name: python3-tripleoclient
        state: latest

    - name: 'Create container image preparation file'
      ansible.builtin.shell: |
        openstack tripleo container image prepare default \
        --local-push-destination \
        --output-env-file containers-prepare-parameter.yaml
