#ansible-playbook -i inventory registration.yaml -u <remote_user> --ask-vault-pass
---
- name: 'Subscribing systems into Red Hat CDN'
  hosts: all
  become: true
  vars_files:
    - vars.yaml ## Using vault file
  tasks:
    - name: 'Perform registration'
      community.general.redhat_subscription:
        state: present
        username: "{{ rh_user }}"
        password: "{{ rh_pass }}"
        
    - name: 'Disable all RHSM repositories'
      community.general.rhsm_repository:
        name: '*'
        state: disabled
